config/routes.rb
Practical3Migrations::Application.routes.draw do
  resources :dealerships
  resources :cars

  root :to => 'welcome#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/dealership.rb
class Dealership < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  # GET /dealerships
  # GET /dealerships.json
  def index
    @dealerships = Dealership.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dealerships }
    end
  end

  # GET /dealerships/1
  # GET /dealerships/1.json
  def show
    @dealership = Dealership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dealership }
    end
  end

  # GET /dealerships/new
  # GET /dealerships/new.json
  def new
    @dealership = Dealership.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dealership }
    end
  end

  # GET /dealerships/1/edit
  def edit
    @dealership = Dealership.find(params[:id])
  end

  # POST /dealerships
  # POST /dealerships.json
  def create
    @dealership = Dealership.new(params[:dealership])

    respond_to do |format|
      if @dealership.save
        format.html { redirect_to @dealership, notice: 'Car dealership was successfully created.' }
        format.json { render json: @dealership, status: :created, location: @dealership }
      else
        format.html { render action: "new" }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dealerships/1
  # PUT /dealerships/1.json
  def update
    @dealership = Dealership.find(params[:id])

    respond_to do |format|
      if @dealership.update_attributes(params[:dealership])
        format.html { redirect_to @dealership, notice: 'Car dealership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealerships/1
  # DELETE /dealerships/1.json
  def destroy
    @dealership = Dealership.find(params[:id])
    @dealership.destroy

    respond_to do |format|
      format.html { redirect_to dealerships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dealerships_helper.rb
module DealershipsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.make %></td>
    <td><%= car.model %></td>
    <td><%= car.price %></td>
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Make:</b>
  <%= @car.make %>
</p>

<p>
  <b>Model:</b>
  <%= @car.model %>
</p>

<p>
  <b>Price:</b>
  <%= @car.price %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/dealerships/_form.html.erb
<%= form_for(@dealership) do |f| %>
  <% if @dealership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dealership.errors.count, "error") %> prohibited this car_dealership from being saved:</h2>

      <ul>
      <% @dealership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dealership %><br />
    <%= f.text_field :dealership %>
  </div>
  <div class="field">
    <%= f.label :contact_numbers %><br />
    <%= f.text_field :contact_numbers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dealerships/edit.html.erb
<h1>Editing dealership</h1>

<%= render 'form' %>

<%= link_to 'Show', @dealership %> |
<%= link_to 'Back', dealerships_path %>

app/views/dealerships/index.html.erb
<h1>Listing car_dealerships</h1>

<table>
  <tr>
    <th>Names</th>
    <th>Contact numbers</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dealerships.each do |dealership| %>
  <tr>
    <td><%= dealership.dealership %></td>
    <td><%= dealership.contact_numbers %></td>
    <td><%= link_to 'Show', dealership %></td>
    <td><%= link_to 'Edit', edit_dealership_path(dealership) %></td>
    <td><%= link_to 'Destroy', dealership, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dealership', new_dealership_path %>

app/views/dealerships/new.html.erb
<h1>New dealership</h1>

<%= render 'form' %>

<%= link_to 'Back', dealerships_path %>

app/views/dealerships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dealerships:</b>
  <%= @dealership.dealership %>
</p>

<p>
  <b>Contact Numbers:</b>
  <%= @dealership.contact_numbers %>
</p>


<%= link_to 'Edit', edit_dealership_path(@dealership) %> |
<%= link_to 'Back', dealerships_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practical3Migrations</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>